#!/bin/bash
#update ns3 script

mpi=0

echo 'Configuring NS3, please wait!'

if [ $mpi -eq 1 ]
then 
	CXXFLAGS="-Wno-error" ./waf configure --build-profile=optimized --enable-examples --enable-mpi
else
	CXXFLAGS="-Wno-error" ./waf configure --build-profile=optimized --enable-examples
fi

echo 'Rebuilding NS3, please wait!'
./waf
